---
- hosts: all
  remote_user: root

  tasks:
    - copy: src=files/nginx-conf/ dest=/etc/nginx/conf.d/
      notify: nginx_restart

    - shell: /usr/local/go/bin/go get -u github.com/eirka/eirka-index
    - shell: /usr/local/go/bin/go get -u github.com/eirka/eirka-get
    - shell: /usr/local/go/bin/go get -u github.com/eirka/eirka-post
    - shell: /usr/local/go/bin/go get -u github.com/eirka/eirka-admin

    - template: src=files/pram.conf.j2 dest=/etc/pram/pram.conf

    - mysql_db: name=eirka state=present
      notify:
        - schema_import
        - service_activation

    - mysql_user: name=pram password="{{ lookup('password', '/tmp/' + ansible_fqdn + '/db_password') }}" host=localhost priv="eirka.*:SELECT,INSERT,UPDATE,DELETE" state=present

  handlers:
    - name: nginx_restart
      service: name=nginx state=restarted

    - name: schema_import
      mysql_db: name=eirka state=import target=/data/pram/src/github.com/eirka/eirka-post/eirka.sql

    - name: service_activation
      service: name={{ item }} state=started enabled=yes
      with_items:
        - eirka-index
        - eirka-get
        - eirka-post
        - eirka-admin
