---
- hosts: all
  remote_user: root

  tasks:
    - lineinfile: dest=/etc/environment state=present line="export GOROOT=/usr/local/go"
    - lineinfile: dest=/etc/environment state=present line="export GOPATH=/data/pram"
    - lineinfile: dest=/etc/environment state=present line="export GOBIN=/data/pram/bin"
    - lineinfile: dest=/root/.profile state=present line="export PATH=$PATH:$GOROOT/bin"

    - file: path=/usr/local/go/ state=absent
    - file: path=/root/go.tar.gz state=absent

    - get_url:
        url: https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
        dest: /root/go.tar.gz
        checksum: sha256:3333f6ea53afa971e9078895eaa4ac7204a8c6b5c68c10e6bc9a33e8e391bdd8

    - unarchive: src=/root/go.tar.gz dest=/usr/local copy=no
