#!/bin/bash
# creates a mysql backup
#
# CREATE USER 'backup'@'localhost';
# GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT ON *.* TO 'backup'@'localhost';
# FLUSH PRIVILEGES;
#
# restore:
# delete the mysql datadir and unzip your backup
# run this command:
# innobackupex --copy-back /data/backups/whatever

# timestamp
DATE=$(date +"%Y%m%d")
# directory
DIR="/data/backups/$DATE"
# archive name
TAR="/data/backups/backup-$DATE.tar.gz"

set -eu
innobackupex --user=backup --no-timestamp $DIR
innobackupex --apply-log /data/backups/$DATE
nice -n 10 tar -cvzf $TAR $DIR
rm -rf $DIR
find /data/backups -mtime +7 -delete
