#!/bin/bash
# creates a mysql backup
#
# CREATE USER 'backup'@'localhost';
# GRANT RELOAD, PROCESS, LOCK TABLES, REPLICATION CLIENT ON *.* TO 'backup'@'localhost';
# FLUSH PRIVILEGES;
#
# restore:
# delete the mysql datadir and unzip your backup
# run this command:
# xtrabackup --copy-back --target-dir=/data/backups/whatever

# timestamp
DATE=$(date +"%Y%m%d")
# directory
DIR="/data/backups/$DATE"
# archive name
TAR="/data/backups/backup-$DATE.tar.gz"

set -eu
xtrabackup --backup --no-server-version-check --user=backup --target-dir=$DIR
xtrabackup --prepare --target-dir=$DIR
nice -n 10 tar -cvzf $TAR $DIR
rm -rf $DIR
find /data/backups -mtime +30 -delete
